### ISSUE TITLE
Decide on what type of application the project will be. (WPF, Windows Forms, etc..)

### ISSUE THREAD

**Issue by iFialAtFail** [iFialAtFail/flammenwerfer#2]

**Comment by iFialAtFail** [comment]
My thoughts are to use windows forms. I think our learning curve is going to be hard enough with the modification of the existing project itself. 

As we are familiar with it, we can focus on the business logic. 

Thoughts?

**Comment by JakJon** [comment]
Yea I agree with windows forms. I was wanting to try to learn a new type but I think we'll have our hands full interperting this code already.

**Comment by ghost** [comment]
I'll go along with whatever you guys want to do.  Windows Forms are fine by me as well.  I took Java and not C# so I'm learning everything on the fly regardless haha.

It seems like the app we are taking on is a little bit different than what was asked for in class as well.  

Are we going to make any updates to how it works in general?

**Comment by iFialAtFail** [comment]
Windows Forms it is then.

Kirk, here's the link to our Discord Server. Please click it when you get the chance. We can do the non-formal discussions on there when not in class. https://discord.gg/4Hwadmz
